# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
  batch: false
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines-build-prr-app.yml
    - README.md
    - SECURITY.md
    - CONTRIBUTING.md

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines-build-prr-app.yml
    - README.md
    - SECURITY.md
    - CONTRIBUTING.md
    
pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

# Comment out as composer expecting 
# - script: composer install --no-interaction --prefer-dist
#   displayName: 'composer install'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      *
      **/css/**
      **/fontawesome/**
      **/fonts/**
      **/js/**
      **/team-photos/**
    TargetFolder: '$(Build.SourcesDirectory)/output'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/output/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop-$(Build.BuildNumber).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop-$(Build.BuildNumber).zip'
    publishLocation: 'Container'



